---
name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -w -n kodiak -i assets/kodiak.icns main.py &&
                cd dist/ &&
                zip -r9 kodiak kodiak.app/
            OUT_FILE_NAME: kodiak.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n kodiak -i assets/kodiak.ico main.py
            OUT_FILE_NAME: kodiak.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: pyinstaller -F -w -n kodiak -i assets/kodiak.ico main.py
            OUT_FILE_NAME: kodiak.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-2

      - name: Install dependencies
        run: poetry config experimental.new-installer false && poetry install

      - name: Build Executable for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - uses: actions/upload-artifact@v3
        with:
          name: Kodiak-${{ runner.os }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
  