---
name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-2

      - name: Install dependencies
        run: poetry config experimental.new-installer false && poetry install

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: true

      - uses: actions/upload-artifact@v3
        with:
          name: Kodiak-${{ runner.os }}
          path: |
            build/Kodiak*.bin
            build/Kodiak*.exe
            build/Kodiak*.app/**/*
 