---
name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-2

      - name: Install dependencies
        run: poetry config experimental.new-installer false && poetry install

      - name: Bundle
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install create-dmg
            poetry run make bundle_mac
          elif [ "$RUNNER_OS" == "Windows" ]; then
            poetry run make bundle_windows
          elif [ "$RUNNER_OS" == "Linux" ]; then
            poetry run make bundle_linux
          fi
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: Kodiak-${{ runner.os }}
          path: |
            dist/Kodiak*-windows.tar.gz
            dist/Kodiak*-windows.exe
            dist/Kodiak*-mac.dmg
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    needs: [ build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/download-artifact@v3
        with:
          name: Kodiak-${{ runner.os }}
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Kodiak*-windows.tar.gz
            Kodiak*-windows.exe
            Kodiak*-mac.dmg
      - name: Upload to Brew
        run: make upload_brew