name: Build and Release Executables

on:
  push:
    branches:
      - main

jobs:
  create_draft_release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true


  build_and_upload_mac:
    name: Build and Upload Mac executable
    runs-on: macos-latest
    needs: create_draft_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Build Linux executable
      #   run: pyinstaller --name "kodiak" --onefile --windowed --icon=assets/kodiak.ico main.py 
      #   if: matrix.os == 'ubuntu-latest'

      - name: Build Executable
        run: |
          pyinstaller --name "kodiak" --onefile --windowed --icon=assets/kodiak.icns main.py
        
      - name: Upload Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: |
            ./dist/kodiak
          asset_name: kodiak.dmg
          asset_content_type: application/x-dmg


  build_and_upload_windows:
    name: Build and Upload Windows exeecutable
    runs-on: windows-latest
    needs: create_draft_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable
        run: |
          pyinstaller --name "kodiak" --onefile --windowed --icon=assets/kodiak.ico main.py 
      
      - name: Upload Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: |
            dist/kodiak
          asset_name: kodiak.exe
          asset_content_type: application/x-msdownload
     

    
 
