name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows executable
        run: pyinstaller --onefile --windowed --icon=assets/kodiak.ico main.py
        if: matrix.os == 'windows-latest'

      - name: Build Linux executable
        run: pyinstaller --onefile --windowed --icon=assets/kodiak.ico main.py
        if: matrix.os == 'ubuntu-latest'

      - name: Build Mac executable
        run: pyinstaller --onefile --windowed --icon=assets/kodiak.icns main.py
        if: matrix.os == 'macos-latest'

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
 